#!/bin/sh

# quit if we're called for the loopback
if [ "$IFACE" = "lo" ]; then
        exit 0
fi

if [ "$PHASE" = "post-up" ]; then
        LOG_FILE=/var/tmp/pluto-network-config.txt
        date >> $LOG_FILE
        echo starting >> $LOG_FILE
        ETH_IP=$(ip -brief address show eth0 | awk '{print $3}' | awk -F/ '{print $1}')
        PLUTO_IP=192.168.2.1
        echo ETHIP=$ETH_IP, PLUTO_IP=$PLUTO_IP, adding rules >> $LOG_FILE
        sudo iptables -t nat -A PREROUTING -p tcp --dport 30431 -j DNAT --to-destination ${PLUTO_IP}:30431
        sudo iptables -t nat -A POSTROUTING -p tcp -d ${PLUTO_IP} --dport 30431 -j SNAT --to-source ${ETH_IP}
        sudo iptables-save >> $LOG_FILE
        echo rules saved, setting ipv4.ip_forward=1 >> $LOG_FILE
        sudo sysctl net.ipv4.ip_forward=1
        echo done >> $LOG_FILE
fi


